name: Generador de APK BIO-BREACH
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Crear APK de BIO-BREACH
        uses: alyossha/html-to-apk@v1.1
        with:
          # Nombre que aparecerá bajo el icono en tu celular
          app_name: 'BIO-BREACH HUB'
          # Carpeta donde está tu index.html (el punto indica la raíz)
          path: '.'

      - name: Guardar el instalador
        uses: actions/upload-artifact@v4
        with:
          name: BIO-BREACH-Instalador-APK
          path: ./*.apk
