name: Compilador BIO-BREACH
on:
  workflow_dispatch: # Esto te permite darle a un bot√≥n para compilar cuando quieras
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalando herramientas
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Empaquetando archivos
        run: |
          # Esto crea un paquete con tu HTML
          zip -r BioBreach.zip ./*

      - name: Subir Resultado
        uses: actions/upload-artifact@v3
        with:
          name: Archivos-App-Web
          path: BioBreach.zip
          
