name: Build Android APK

on:
  push:
    branches: [ main ] # Se activa cada vez que subes algo a la rama main

jobs:
  build:
    runs-on: ubuntu-latest # La máquina virtual usará Linux

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar dependencias
        run: npm install

      - name: Sincronizar HTML con Android
        run: npx cap sync android

      - name: Compilar APK (Debug)
        run: cd android && ./gradlew assembleDebug

      - name: Subir el archivo resultante
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
