name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4 # <--- ACTUALIZADO A V4

      - name: Instalar Java
        uses: actions/setup-java@v4 # <--- ACTUALIZADO A V4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar dependencias
        run: npm install

      - name: Sincronizar HTML con Android
        run: npx cap sync android

      - name: Compilar APK (Debug)
        run: cd android && ./gradlew assembleDebug

      - name: Subir el archivo resultante
        uses: actions/upload-artifact@v4 # <--- ACTUALIZADO A V4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
